# -*- coding: utf-8 -*-
"""rl_agents

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O_19EjpZrCRADIJUvnKFcVZrwebSAQFE

# rl_agents.py
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torch.distributions as dist
import numpy as np
import random
from collections import deque

# Базовые нейросетевые компоненты
# Все сети принимают на вход словарь состояния, содержащий:
#   current      – индекс текущего города (int -> later one-hot)
#   visited_mask – бинарный вектор посещённых городов (1 = посещён)
#   dist_vector  – нормализованные расстояния от текущего города до всех
# Размер входа: 3 * n_warehouses (one-hot + visited_mask + dist_vector)

class PolicyNetwork(nn.Module):
    """
    Нейросеть политики (Actor) для дискретного пространства действий.
    Используется в алгоритмах Policy Gradient, A2C, PPO и SAC.
    Возвращает вероятности выбора каждого из оставшихся (непосещённых) городов.
    """
    def __init__(self, n_warehouses, hidden_size=128):
        super().__init__()
        self.n_warehouses = n_warehouses
        # Три компоненты входа: one_hot(current), visited_mask, dist_vector
        self.network = nn.Sequential(
            nn.Linear(n_warehouses * 3, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, n_warehouses)   # логиты для каждого действия
        )

    def forward(self, state):
        """
        state: словарь с ключами 'current', 'visited_mask', 'dist_vector'.
        Возвращает softmax-вероятности (маска посещённых зануляется).
        """
        current = state['current']                  # (batch,)
        visited_mask = state['visited_mask']         # (batch, n)
        dist_vector = state['dist_vector']           # (batch, n)
        # One-hot encoding текущего города
        current_onehot = torch.zeros(current.shape[0], self.n_warehouses, device=current.device)
        current_onehot.scatter_(1, current.unsqueeze(1), 1.0)
        # Конкатенация признаков
        x = torch.cat([current_onehot, visited_mask, dist_vector], dim=1)
        logits = self.network(x)
        # Запрещаем выбор уже посещённых городов
        logits[visited_mask.bool()] = -1e9
        return torch.softmax(logits, dim=-1)


class QNetwork(nn.Module):
    """
    Нейросеть для оценки Q-функции (Critic).
    Возвращает вектор Q-значений для каждого возможного действия.
    Используется в DQN, Double DQN и SAC.
    """
    def __init__(self, n_warehouses, hidden_size=128):
        super().__init__()
        self.n_warehouses = n_warehouses
        # Аналогичный вход: current_onehot + visited_mask + dist_vector
        self.network = nn.Sequential(
            nn.Linear(n_warehouses * 3, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, n_warehouses)   # Q-значения для каждого действия
        )

    def forward(self, state):
        current = state['current']
        visited_mask = state['visited_mask']
        dist_vector = state['dist_vector']
        current_onehot = torch.zeros(current.shape[0], self.n_warehouses, device=current.device)
        current_onehot.scatter_(1, current.unsqueeze(1), 1.0)
        x = torch.cat([current_onehot, visited_mask, dist_vector], dim=1)
        q_values = self.network(x)
        # Обнуляем Q для недоступных действий
        q_values[visited_mask.bool()] = -1e9
        return q_values


class ActorCriticNetwork(nn.Module):
    """
    Объединённая сеть Actor‑Critic с общим энкодером.
    Возвращает вероятности действий (Actor) и оценку ценности состояния V(s) (Critic).
    Применяется в A2C и PPO.
    """
    def __init__(self, n_warehouses, hidden_size=128):
        super().__init__()
        self.n_warehouses = n_warehouses
        # Общий энкодер для извлечения признаков
        self.encoder = nn.Sequential(
            nn.Linear(n_warehouses * 3, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, hidden_size),
            nn.ReLU()
        )
        self.actor = nn.Linear(hidden_size, n_warehouses)   # логиты действий
        self.critic = nn.Linear(hidden_size, 1)             # оценка V(s)

    def forward(self, state):
        current = state['current']
        visited_mask = state['visited_mask']
        dist_vector = state['dist_vector']
        current_onehot = torch.zeros(current.shape[0], self.n_warehouses, device=current.device)
        current_onehot.scatter_(1, current.unsqueeze(1), 1.0)
        x = torch.cat([current_onehot, visited_mask, dist_vector], dim=1)
        features = self.encoder(x)
        logits = self.actor(features)
        # Маскируем невозможные действия
        logits[visited_mask.bool()] = -1e9
        action_probs = torch.softmax(logits, dim=-1)
        state_value = self.critic(features)
        return action_probs, state_value

# Улучшенные архитектуры
# Все они получают на вход состояние, содержащее:
#   current (индекс текущего города),
#   visited_mask (маска уже посещённых),
#   dist_vector (нормализованные расстояния от текущего города до всех).
class EnhancedPolicyNetwork(nn.Module):
    """
    Улучшенная сеть политики (Actor) с LayerNorm, Dropout и Xavier-инициализацией.
    Используется в алгоритмах Policy Gradient, A2C, PPO, SAC.
    """
    def __init__(self, n_warehouses, hidden_size=256):
        super().__init__()
        self.n_warehouses = n_warehouses
        self.network = nn.Sequential(
            nn.Linear(n_warehouses * 3, hidden_size),
            nn.LayerNorm(hidden_size),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(hidden_size, hidden_size),
            nn.LayerNorm(hidden_size),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(hidden_size, n_warehouses)
        )
        self._init_weights()

    def _init_weights(self):
        """Инициализация весов методом Xavier и небольшое начальное смещение."""
        for layer in self.network:
            if isinstance(layer, nn.Linear):
                nn.init.xavier_uniform_(layer.weight)
                nn.init.constant_(layer.bias, 0.01)

    def forward(self, state):
        # Преобразование состояния в тензоры: one-hot текущего узла + маска посещённых + вектор расстояний
        current = state['current']
        visited_mask = state['visited_mask']
        dist_vector = state['dist_vector']
        current_onehot = torch.zeros(current.shape[0], self.n_warehouses, device=current.device)
        current_onehot.scatter_(1, current.unsqueeze(1), 1.0)
        x = torch.cat([current_onehot, visited_mask, dist_vector], dim=1)
        logits = self.network(x)
        # Запрещаем выбор уже посещённых городов
        logits[visited_mask.bool()] = -1e9
        return torch.softmax(logits, dim=-1)


class EnhancedActorCriticNetwork(nn.Module):
    """
    Улучшенная сеть Actor-Critic с общим энкодером, нормализацией и Xavier-инициализацией.
    Возвращает вероятности действий (Actor) и оценку ценности состояния (Critic).
    """
    def __init__(self, n_warehouses, hidden_size=256):
        super().__init__()
        self.n_warehouses = n_warehouses
        self.encoder = nn.Sequential(
            nn.Linear(n_warehouses * 3, hidden_size),
            nn.LayerNorm(hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, hidden_size),
            nn.LayerNorm(hidden_size),
            nn.ReLU()
        )
        self.actor = nn.Sequential(
            nn.Linear(hidden_size, hidden_size // 2),
            nn.ReLU(),
            nn.Linear(hidden_size // 2, n_warehouses)
        )
        self.critic = nn.Sequential(
            nn.Linear(hidden_size, hidden_size // 2),
            nn.ReLU(),
            nn.Linear(hidden_size // 2, 1)
        )
        self._init_weights()

    def _init_weights(self):
        """Xavier-инициализация всех линейных слоёв."""
        for module in [self.encoder, self.actor, self.critic]:
            for layer in module:
                if isinstance(layer, nn.Linear):
                    nn.init.xavier_uniform_(layer.weight)
                    nn.init.constant_(layer.bias, 0.01)

    def forward(self, state):
        current = state['current']
        visited_mask = state['visited_mask']
        dist_vector = state['dist_vector']
        current_onehot = torch.zeros(current.shape[0], self.n_warehouses, device=current.device)
        current_onehot.scatter_(1, current.unsqueeze(1), 1.0)
        x = torch.cat([current_onehot, visited_mask, dist_vector], dim=1)
        features = self.encoder(x)
        logits = self.actor(features)
        logits[visited_mask.bool()] = -1e9
        action_probs = torch.softmax(logits, dim=-1)
        state_value = self.critic(features)
        return action_probs, state_value


class DuelingQNetwork(nn.Module):
    """
    Дуэльная Q-сеть: раздельная оценка ценности состояния V(s) и преимуществ A(s,a).
    Q(s,a) = V(s) + A(s,a) - mean(A(s,:)).
    Используется в ImprovedDQN и ImprovedDoubleDQN.
    """
    def __init__(self, n_warehouses, hidden_size=256):
        super().__init__()
        self.n_warehouses = n_warehouses
        self.encoder = nn.Sequential(
            nn.Linear(n_warehouses * 3, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, hidden_size),
            nn.ReLU()
        )
        self.value_stream = nn.Sequential(
            nn.Linear(hidden_size, hidden_size // 2),
            nn.ReLU(),
            nn.Linear(hidden_size // 2, 1)
        )
        self.advantage_stream = nn.Sequential(
            nn.Linear(hidden_size, hidden_size // 2),
            nn.ReLU(),
            nn.Linear(hidden_size // 2, n_warehouses)
        )

    def forward(self, state):
        current = state['current']
        visited_mask = state['visited_mask']
        dist_vector = state['dist_vector']
        current_onehot = torch.zeros(current.shape[0], self.n_warehouses, device=current.device)
        current_onehot.scatter_(1, current.unsqueeze(1), 1.0)
        x = torch.cat([current_onehot, visited_mask, dist_vector], dim=1)
        features = self.encoder(x)
        value = self.value_stream(features)
        advantage = self.advantage_stream(features)
        # Комбинируем с вычитанием среднего для устойчивости
        q_values = value + advantage - advantage.mean(dim=1, keepdim=True)
        q_values[visited_mask.bool()] = -1e9
        return q_values


class NoisyLinear(nn.Module):
    """
    Линейный слой с параметрическим шумом (Noisy Networks).
    Улучшает исследование за счёт шума в весах и смещениях.
    """
    def __init__(self, in_features, out_features, std_init=0.4):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.std_init = std_init

        self.weight_mu = nn.Parameter(torch.Tensor(out_features, in_features))
        self.weight_sigma = nn.Parameter(torch.Tensor(out_features, in_features))
        self.register_buffer('weight_epsilon', torch.Tensor(out_features, in_features))

        self.bias_mu = nn.Parameter(torch.Tensor(out_features))
        self.bias_sigma = nn.Parameter(torch.Tensor(out_features))
        self.register_buffer('bias_epsilon', torch.Tensor(out_features))

        self.reset_parameters()
        self.reset_noise()

    def reset_parameters(self):
        mu_range = 1 / np.sqrt(self.in_features)
        self.weight_mu.data.uniform_(-mu_range, mu_range)
        self.weight_sigma.data.fill_(self.std_init / np.sqrt(self.in_features))
        self.bias_mu.data.uniform_(-mu_range, mu_range)
        self.bias_sigma.data.fill_(self.std_init / np.sqrt(self.out_features))

    def reset_noise(self):
        epsilon_in = self._scale_noise(self.in_features)
        epsilon_out = self._scale_noise(self.out_features)
        self.weight_epsilon.copy_(epsilon_out.ger(epsilon_in))
        self.bias_epsilon.copy_(epsilon_out)

    def _scale_noise(self, size):
        x = torch.randn(size)
        return x.sign().mul(x.abs().sqrt())

    def forward(self, x):
        if self.training:
            weight = self.weight_mu + self.weight_sigma * self.weight_epsilon
            bias = self.bias_mu + self.bias_sigma * self.bias_epsilon
        else:
            weight = self.weight_mu
            bias = self.bias_mu
        return nn.functional.linear(x, weight, bias)


class NoisyDuelingQNetwork(nn.Module):
    """
    Дуэльная Q-сеть с Noisy Linear слоями для улучшенного исследования (Noisy Dueling DQN).
    """
    def __init__(self, n_warehouses, hidden_size=256):
        super().__init__()
        self.n_warehouses = n_warehouses
        self.encoder = nn.Sequential(
            NoisyLinear(n_warehouses * 3, hidden_size),
            nn.ReLU(),
            NoisyLinear(hidden_size, hidden_size),
            nn.ReLU()
        )
        self.value_stream = nn.Sequential(
            NoisyLinear(hidden_size, hidden_size // 2),
            nn.ReLU(),
            NoisyLinear(hidden_size // 2, 1)
        )
        self.advantage_stream = nn.Sequential(
            NoisyLinear(hidden_size, hidden_size // 2),
            nn.ReLU(),
            NoisyLinear(hidden_size // 2, n_warehouses)
        )

    def forward(self, state):
        current = state['current']
        visited_mask = state['visited_mask']
        dist_vector = state['dist_vector']
        current_onehot = torch.zeros(current.shape[0], self.n_warehouses, device=current.device)
        current_onehot.scatter_(1, current.unsqueeze(1), 1.0)
        x = torch.cat([current_onehot, visited_mask, dist_vector], dim=1)
        features = self.encoder(x)
        value = self.value_stream(features)
        advantage = self.advantage_stream(features)
        q_values = value + advantage - advantage.mean(dim=1, keepdim=True)
        q_values[visited_mask.bool()] = -1e9
        return q_values

    def reset_noise(self):
        """Сброс шумовых переменных во всех Noisy-слоях."""
        for module in self.modules():
            if isinstance(module, NoisyLinear):
                module.reset_noise()


class EnhancedSACNetwork(nn.Module):
    """
    Улучшенная Q-сеть для SAC с нормализацией, Dropout и Xavier-инициализацией.
    Использует дуэльную архитектуру.
    """
    def __init__(self, n_warehouses, hidden_size=256):
        super().__init__()
        self.n_warehouses = n_warehouses
        self.encoder = nn.Sequential(
            nn.Linear(n_warehouses * 3, hidden_size),
            nn.LayerNorm(hidden_size),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(hidden_size, hidden_size),
            nn.LayerNorm(hidden_size),
            nn.ReLU(),
            nn.Dropout(0.1)
        )
        self.value_stream = nn.Sequential(
            nn.Linear(hidden_size, hidden_size // 2),
            nn.ReLU(),
            nn.Linear(hidden_size // 2, 1)
        )
        self.advantage_stream = nn.Sequential(
            nn.Linear(hidden_size, hidden_size // 2),
            nn.ReLU(),
            nn.Linear(hidden_size // 2, n_warehouses)
        )
        self._init_weights()

    def _init_weights(self):
        for module in [self.encoder, self.value_stream, self.advantage_stream]:
            for layer in module:
                if isinstance(layer, nn.Linear):
                    nn.init.xavier_uniform_(layer.weight)
                    nn.init.constant_(layer.bias, 0.01)

    def forward(self, state):
        current = state['current']
        visited_mask = state['visited_mask']
        dist_vector = state['dist_vector']
        current_onehot = torch.zeros(current.shape[0], self.n_warehouses, device=current.device)
        current_onehot.scatter_(1, current.unsqueeze(1), 1.0)
        x = torch.cat([current_onehot, visited_mask, dist_vector], dim=1)
        features = self.encoder(x)
        value = self.value_stream(features)
        advantage = self.advantage_stream(features)
        q_values = value + advantage - advantage.mean(dim=1, keepdim=True)
        q_values[visited_mask.bool()] = -1e9
        return q_values


class PrioritizedReplayBuffer:
    """
    Буфер воспроизведения с приоритезацией опыта.
    Хранит переходы и позволяет сэмплировать их с вероятностью,
    пропорциональной TD-ошибке. Ускоряет обучение, фокусируясь на важных примерах.
    """
    def __init__(self, capacity=10000, alpha=0.6):
        self.capacity = capacity
        self.alpha = alpha          # степень приоритезации (0 - нет, 1 - полная)
        self.buffer = []
        self.priorities = np.zeros(capacity, dtype=np.float32)
        self.position = 0
        self.size = 0

    def __len__(self):
        return self.size

    def add(self, experience, priority=None):
        """Добавление перехода с заданным или максимальным приоритетом."""
        if priority is None:
            priority = self.max_priority()
        if len(self.buffer) < self.capacity:
            self.buffer.append(experience)
        else:
            self.buffer[self.position] = experience
        self.priorities[self.position] = priority ** self.alpha
        self.position = (self.position + 1) % self.capacity
        self.size = min(self.size + 1, self.capacity)

    def sample(self, batch_size, beta=0.4):
        """Сэмплирование батча с учётом приоритетов и расчёт весов для коррекции смещения."""
        if self.size == 0:
            return [], [], []
        probs = self.priorities[:self.size] / self.priorities[:self.size].sum()
        indices = np.random.choice(self.size, min(batch_size, self.size), p=probs, replace=False)
        weights = (self.size * probs[indices]) ** (-beta)
        weights = weights / weights.max()
        batch = [self.buffer[i] for i in indices]
        return batch, indices, weights

    def update_priorities(self, indices, priorities):
        """Обновление приоритетов для указанных индексов."""
        for idx, priority in zip(indices, priorities):
            self.priorities[idx] = (priority + 1e-5) ** self.alpha

    def max_priority(self):
        """Возвращает текущий максимальный приоритет."""
        return self.priorities[:self.size].max() if self.size > 0 else 1.0

# Агенты

class PolicyGradientAgent:
    """
    Агент на основе метода Policy Gradient (REINFORCE) с базовым уровнем.
    Собирает логарифмы вероятностей и награды за эпизод, затем обновляет политику
    с помощью градиентного подъёма по ожидаемому дисконтированному доходу.
    """
    def __init__(self, n_warehouses, learning_rate=0.001):
        self.policy_network = PolicyNetwork(n_warehouses)          # Actor
        self.optimizer = optim.Adam(self.policy_network.parameters(), lr=learning_rate)
        self.saved_log_probs = []   # логарифмы вероятностей выбранных действий
        self.rewards = []           # пошаговые награды

    def select_action(self, state):
        """
        Выбирает действие сэмплированием из распределения политики.
        Сохраняет логарифм вероятности для последующего обучения.
        """
        state_tensor = {
            'current': torch.tensor([state['current']], dtype=torch.long),
            'visited_mask': torch.tensor([state['visited_mask']], dtype=torch.float32),
            'dist_vector': torch.tensor([state['dist_vector']], dtype=torch.float32)
        }
        probs = self.policy_network(state_tensor)                  # (1, n_nodes)
        m = dist.Categorical(probs)
        action = m.sample()
        self.saved_log_probs.append(m.log_prob(action))
        return action.item()

    def update(self):
        """
        Вычисляет дисконтированные возвраты, нормализует их и применяет
        градиентный шаг REINFORCE: loss = -log_prob * return.
        """
        if not self.rewards:
            return
        R = 0
        returns = []
        for r in reversed(self.rewards):
            R = r + 0.99 * R
            returns.insert(0, R)
        returns = torch.tensor(returns)
        returns = (returns - returns.mean()) / (returns.std() + 1e-9)
        policy_loss = []
        for log_prob, R in zip(self.saved_log_probs, returns):
            policy_loss.append(-log_prob * R)
        self.optimizer.zero_grad()
        loss = torch.stack(policy_loss).sum()
        loss.backward()
        self.optimizer.step()
        self.saved_log_probs = []
        self.rewards = []


class A2CAgent:
    """
    Advantage Actor‑Critic (A2C). Использует actor‑critic архитектуру,
    где critic оценивает функцию ценности V(s), а actor обновляется
    с использованием преимущества A(s,a) = R - V(s).
    """
    def __init__(self, n_warehouses, learning_rate=0.001, gamma=0.99):
        self.actor_critic = ActorCriticNetwork(n_warehouses)
        self.optimizer = optim.Adam(self.actor_critic.parameters(), lr=learning_rate)
        self.gamma = gamma
        self.saved_log_probs = []   # log_prob действий
        self.rewards = []           # пошаговые награды
        self.state_values = []      # оценки V(s) от критика

    def select_action(self, state):
        """Выбирает действие, сохраняет log_prob и V(s)."""
        state_tensor = {
            'current': torch.tensor([state['current']], dtype=torch.long),
            'visited_mask': torch.tensor([state['visited_mask']], dtype=torch.float32),
            'dist_vector': torch.tensor([state['dist_vector']], dtype=torch.float32)
        }
        probs, state_value = self.actor_critic(state_tensor)
        m = dist.Categorical(probs)
        action = m.sample()
        self.saved_log_probs.append(m.log_prob(action))
        self.state_values.append(state_value)
        return action.item()

    def update(self):
        """
        Вычисляет преимущества, суммирует лоссы политики и ценности,
        выполняет градиентный шаг.
        """
        if not self.rewards:
            return
        R = 0
        returns = []
        for r in reversed(self.rewards):
            R = r + self.gamma * R
            returns.insert(0, R)
        returns = torch.tensor(returns)
        returns = (returns - returns.mean()) / (returns.std() + 1e-9)
        state_values = torch.cat(self.state_values)
        advantages = returns - state_values.squeeze()
        policy_loss = []
        for log_prob, adv in zip(self.saved_log_probs, advantages):
            policy_loss.append(-log_prob * adv.detach())
        value_loss = nn.MSELoss()(state_values.squeeze(), returns)
        self.optimizer.zero_grad()
        loss = torch.stack(policy_loss).sum() + value_loss
        loss.backward()
        self.optimizer.step()
        self.saved_log_probs = []
        self.rewards = []
        self.state_values = []


class PPOAgent:
    """
    Proximal Policy Optimization (PPO) с корректным распределением наград по шагам.
    Сохраняет пошаговые вознаграждения и флаги завершения, затем вычисляет
    дисконтированные возвраты с учётом done. Используется несколько эпох обновления
    для стабильности.
    """
    def __init__(self, n_warehouses, learning_rate=0.001, gamma=0.99, clip_epsilon=0.2):
        self.actor_critic = ActorCriticNetwork(n_warehouses)
        self.optimizer = optim.Adam(self.actor_critic.parameters(), lr=learning_rate)
        self.gamma = gamma
        self.clip_epsilon = clip_epsilon
        self.memory = []   # хранит переходы для всего эпизода

    def select_action(self, state):
        """Выбирает действие, сохраняет переход с пустой наградой (будет заполнена позже)."""
        state_tensor = {
            'current': torch.tensor([state['current']], dtype=torch.long),
            'visited_mask': torch.tensor([state['visited_mask']], dtype=torch.float32),
            'dist_vector': torch.tensor([state['dist_vector']], dtype=torch.float32)
        }
        with torch.no_grad():
            probs, state_value = self.actor_critic(state_tensor)
            m = dist.Categorical(probs)
            action = m.sample()
        self.memory.append({
            'state': state_tensor,
            'action': action,
            'log_prob': m.log_prob(action),
            'value': state_value,
            'reward': 0.0,      # будет заполнено позже
            'done': False
        })
        return action.item()

    def set_last_reward(self, reward, done):
        """
        Вызывается после env.step для последнего добавленного перехода.
        Заполняет reward и done.
        """
        if self.memory:
            self.memory[-1]['reward'] = reward
            self.memory[-1]['done'] = done

    def update(self):
        """
        Вычисляет returns и преимущества, затем выполняет несколько эпох
        PPO‑обновления (clipped surrogate objective + value loss).
        """
        if not self.memory:
            return
        rewards = [m['reward'] for m in self.memory]
        dones = [m['done'] for m in self.memory]
        states = [m['state'] for m in self.memory]
        actions = torch.stack([m['action'] for m in self.memory])
        old_log_probs = torch.stack([m['log_prob'] for m in self.memory])
        old_values = torch.cat([m['value'] for m in self.memory])

        # вычисляем returns с учётом done
        returns = []
        R = 0
        for r, d in zip(reversed(rewards), reversed(dones)):
            if d:
                R = 0                   # сброс на границе эпизода (если done=True)
            R = r + self.gamma * R
            returns.insert(0, R)
        returns = torch.tensor(returns, dtype=torch.float32)
        advantages = returns - old_values.squeeze()
        advantages = (advantages - advantages.mean()) / (advantages.std() + 1e-8)

        # Несколько эпох обучения на одном и том же эпизоде
        for _ in range(3):
            new_log_probs = []
            new_values = []
            for i, state in enumerate(states):
                probs, value = self.actor_critic(state)
                dist_ = dist.Categorical(probs)
                new_log_probs.append(dist_.log_prob(actions[i]))
                new_values.append(value)
            new_log_probs = torch.stack(new_log_probs)
            new_values = torch.cat(new_values)
            ratio = (new_log_probs - old_log_probs).exp()
            surr1 = ratio * advantages
            surr2 = torch.clamp(ratio, 1 - self.clip_epsilon, 1 + self.clip_epsilon) * advantages
            policy_loss = -torch.min(surr1, surr2).mean()
            value_loss = nn.MSELoss()(new_values.squeeze(), returns)
            loss = policy_loss + 0.5 * value_loss
            self.optimizer.zero_grad()
            loss.backward()
            self.optimizer.step()
        self.memory = []


class DQNAgent:
    """
    Deep Q‑Network (DQN). Аппроксимирует Q‑функцию, использует целевую сеть
    и experience replay. Выбор действия – ε‑greedy.
    """
    def __init__(self, n_warehouses, learning_rate=0.001, gamma=0.99, epsilon=1.0, epsilon_decay=0.995):
        self.q_network = QNetwork(n_warehouses)
        self.target_network = QNetwork(n_warehouses)
        self.target_network.load_state_dict(self.q_network.state_dict())
        self.optimizer = optim.Adam(self.q_network.parameters(), lr=learning_rate)
        self.gamma = gamma
        self.epsilon = epsilon
        self.epsilon_decay = epsilon_decay
        self.memory = deque(maxlen=10000)
        self.batch_size = 32

    def select_action(self, state):
        """ε‑greedy выбор действия."""
        if random.random() < self.epsilon:
            visited = state['visited_mask']
            valid = [i for i, v in enumerate(visited) if v == 0]
            return random.choice(valid) if valid else 0
        state_tensor = {
            'current': torch.tensor([state['current']], dtype=torch.long),
            'visited_mask': torch.tensor([state['visited_mask']], dtype=torch.float32),
            'dist_vector': torch.tensor([state['dist_vector']], dtype=torch.float32)
        }
        with torch.no_grad():
            q_values = self.q_network(state_tensor)
            return q_values.argmax().item()

    def store_experience(self, state, action, reward, next_state, done):
        """Сохраняет переход в replay-буфер."""
        self.memory.append((state, action, reward, next_state, done))

    def update(self):
        """Один шаг обучения по мини-батчу из replay-буфера."""
        if len(self.memory) < self.batch_size:
            return
        batch = random.sample(self.memory, self.batch_size)
        states, actions, rewards, next_states, dones = zip(*batch)
        state_current = torch.tensor([s['current'] for s in states], dtype=torch.long)
        state_visited = torch.tensor([s['visited_mask'] for s in states], dtype=torch.float32)
        state_distvec = torch.tensor([s['dist_vector'] for s in states], dtype=torch.float32)
        next_current = torch.tensor([s['current'] for s in next_states], dtype=torch.long)
        next_visited = torch.tensor([s['visited_mask'] for s in next_states], dtype=torch.float32)
        next_distvec = torch.tensor([s['dist_vector'] for s in next_states], dtype=torch.float32)
        state_tensors = {'current': state_current, 'visited_mask': state_visited, 'dist_vector': state_distvec}
        next_tensors = {'current': next_current, 'visited_mask': next_visited, 'dist_vector': next_distvec}
        actions = torch.tensor(actions)
        rewards = torch.tensor(rewards, dtype=torch.float32)
        dones = torch.tensor(dones, dtype=torch.float32)
        with torch.no_grad():
            next_q = self.target_network(next_tensors).max(1)[0]
            targets = rewards + self.gamma * next_q * (1 - dones)
        current_q = self.q_network(state_tensors)[torch.arange(self.batch_size), actions]
        loss = nn.MSELoss()(current_q, targets)
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()
        self.epsilon = max(0.01, self.epsilon * self.epsilon_decay)
        if random.random() < 0.01:
            self.target_network.load_state_dict(self.q_network.state_dict())


class DoubleDQNAgent(DQNAgent):
    """
    Double DQN. Разделяет выбор действия и оценку Q‑значения,
    чтобы уменьшить завышение оценок.
    """
    def update(self):
        if len(self.memory) < self.batch_size:
            return
        batch = random.sample(self.memory, self.batch_size)
        states, actions, rewards, next_states, dones = zip(*batch)
        state_current = torch.tensor([s['current'] for s in states], dtype=torch.long)
        state_visited = torch.tensor([s['visited_mask'] for s in states], dtype=torch.float32)
        state_distvec = torch.tensor([s['dist_vector'] for s in states], dtype=torch.float32)
        next_current = torch.tensor([s['current'] for s in next_states], dtype=torch.long)
        next_visited = torch.tensor([s['visited_mask'] for s in next_states], dtype=torch.float32)
        next_distvec = torch.tensor([s['dist_vector'] for s in next_states], dtype=torch.float32)
        state_tensors = {'current': state_current, 'visited_mask': state_visited, 'dist_vector': state_distvec}
        next_tensors = {'current': next_current, 'visited_mask': next_visited, 'dist_vector': next_distvec}
        actions = torch.tensor(actions)
        rewards = torch.tensor(rewards, dtype=torch.float32)
        dones = torch.tensor(dones, dtype=torch.float32)
        with torch.no_grad():
            # Выбираем действие по основной сети
            next_actions = self.q_network(next_tensors).argmax(1)
            # Оцениваем его по целевой сети
            next_q = self.target_network(next_tensors)[torch.arange(self.batch_size), next_actions]
            targets = rewards + self.gamma * next_q * (1 - dones)
        current_q = self.q_network(state_tensors)[torch.arange(self.batch_size), actions]
        loss = nn.MSELoss()(current_q, targets)
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()
        self.epsilon = max(0.01, self.epsilon * self.epsilon_decay)
        if random.random() < 0.01:
            self.target_network.load_state_dict(self.q_network.state_dict())


class SACAgent:
    """
    Soft Actor‑Critic (SAC) для дискретных действий.
    Максимизирует и награду, и энтропию политики.
    Использует два критика для уменьшения завышения Q‑значений.
    """
    def __init__(self, n_warehouses, learning_rate=0.001, gamma=0.99, alpha=0.2):
        self.actor = PolicyNetwork(n_warehouses)
        self.critic1 = QNetwork(n_warehouses)
        self.critic2 = QNetwork(n_warehouses)
        self.actor_optimizer = optim.Adam(self.actor.parameters(), lr=learning_rate)
        self.critic1_optimizer = optim.Adam(self.critic1.parameters(), lr=learning_rate)
        self.critic2_optimizer = optim.Adam(self.critic2.parameters(), lr=learning_rate)
        self.gamma = gamma
        self.alpha = alpha          # коэффициент энтропии
        self.memory = deque(maxlen=10000)
        self.batch_size = 32

    def select_action(self, state):
        """Сэмплирует действие из политики."""
        state_tensor = {
            'current': torch.tensor([state['current']], dtype=torch.long),
            'visited_mask': torch.tensor([state['visited_mask']], dtype=torch.float32),
            'dist_vector': torch.tensor([state['dist_vector']], dtype=torch.float32)
        }
        with torch.no_grad():
            probs = self.actor(state_tensor)
            m = dist.Categorical(probs)
            action = m.sample()
        return action.item()

    def store_experience(self, state, action, reward, next_state, done):
        """Сохраняет переход в replay-буфер."""
        self.memory.append((state, action, reward, next_state, done))

    def update(self):
        """
        Обучает обоих критиков и актора с использованием энтропийного бонуса.
        """
        if len(self.memory) < self.batch_size:
            return
        batch = random.sample(self.memory, self.batch_size)
        states, actions, rewards, next_states, dones = zip(*batch)
        state_current = torch.tensor([s['current'] for s in states], dtype=torch.long)
        state_visited = torch.tensor([s['visited_mask'] for s in states], dtype=torch.float32)
        state_distvec = torch.tensor([s['dist_vector'] for s in states], dtype=torch.float32)
        next_current = torch.tensor([s['current'] for s in next_states], dtype=torch.long)
        next_visited = torch.tensor([s['visited_mask'] for s in next_states], dtype=torch.float32)
        next_distvec = torch.tensor([s['dist_vector'] for s in next_states], dtype=torch.float32)
        state_tensors = {'current': state_current, 'visited_mask': state_visited, 'dist_vector': state_distvec}
        next_tensors = {'current': next_current, 'visited_mask': next_visited, 'dist_vector': next_distvec}
        actions = torch.tensor(actions)
        rewards = torch.tensor(rewards, dtype=torch.float32)
        dones = torch.tensor(dones, dtype=torch.float32)
        with torch.no_grad():
            next_probs = self.actor(next_tensors)
            next_log_probs = torch.log(next_probs + 1e-8)
            next_q1 = self.critic1(next_tensors)
            next_q2 = self.critic2(next_tensors)
            next_q = torch.min(next_q1, next_q2)
            next_value = (next_probs * (next_q - self.alpha * next_log_probs)).sum(dim=1)
            targets = rewards + self.gamma * next_value * (1 - dones)
        current_q1 = self.critic1(state_tensors)[torch.arange(self.batch_size), actions]
        current_q2 = self.critic2(state_tensors)[torch.arange(self.batch_size), actions]
        critic1_loss = nn.MSELoss()(current_q1, targets)
        critic2_loss = nn.MSELoss()(current_q2, targets)
        self.critic1_optimizer.zero_grad()
        critic1_loss.backward()
        self.critic1_optimizer.step()
        self.critic2_optimizer.zero_grad()
        critic2_loss.backward()
        self.critic2_optimizer.step()
        probs = self.actor(state_tensors)
        log_probs = torch.log(probs + 1e-8)
        with torch.no_grad():
            q1 = self.critic1(state_tensors)
            q2 = self.critic2(state_tensors)
            q = torch.min(q1, q2)
        actor_loss = (probs * (self.alpha * log_probs - q)).sum(dim=1).mean()
        self.actor_optimizer.zero_grad()
        actor_loss.backward()
        self.actor_optimizer.step()

# Улучшенные агенты
# Все они используют улучшенные нейросетевые архитектуры (Enhanced*),
# современные техники: AdamW, cosine annealing, gradient clipping,
# энтропийную регуляризацию, Prioritized Experience Replay, Noisy сети.

class EnhancedPolicyGradientAgent:
    """
    Улучшенный Policy Gradient (REINFORCE) с энтропийной регуляризацией,
    косинусным отжигом learning rate и gradient clipping.
    """
    def __init__(self, n_warehouses, learning_rate=0.001, gamma=0.99, entropy_coef=0.01):
        self.policy_network = EnhancedPolicyNetwork(n_warehouses)  # улучшенная сеть политики
        self.optimizer = optim.AdamW(self.policy_network.parameters(), lr=learning_rate, weight_decay=1e-4)
        self.scheduler = optim.lr_scheduler.CosineAnnealingLR(self.optimizer, T_max=1500)
        self.gamma = gamma
        self.entropy_coef = entropy_coef
        self.saved_log_probs = []   # log_prob выбранных действий
        self.rewards = []           # пошаговые награды
        self.entropies = []         # энтропия распределения для бонуса

    def select_action(self, state):
        """Выбирает действие, сохраняет log_prob и энтропию."""
        state_tensor = {
            'current': torch.tensor([state['current']], dtype=torch.long),
            'visited_mask': torch.tensor([state['visited_mask']], dtype=torch.float32),
            'dist_vector': torch.tensor([state['dist_vector']], dtype=torch.float32)
        }
        probs = self.policy_network(state_tensor)
        m = dist.Categorical(probs)
        action = m.sample()
        self.saved_log_probs.append(m.log_prob(action))
        self.entropies.append(m.entropy())
        return action.item()

    def update(self):
        """
        Вычисляет дисконтированные возвраты, нормализует их и применяет
        градиентный шаг с энтропийным бонусом.
        """
        if not self.rewards:
            return
        R = 0
        returns = []
        for r in reversed(self.rewards):
            R = r + self.gamma * R
            returns.insert(0, R)
        returns = torch.tensor(returns)
        returns = (returns - returns.mean()) / (returns.std() + 1e-8)
        policy_loss = []
        for log_prob, R in zip(self.saved_log_probs, returns):
            policy_loss.append(-log_prob * R)
        entropy = torch.stack(self.entropies).sum()
        loss = torch.stack(policy_loss).sum() - self.entropy_coef * entropy
        self.optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(self.policy_network.parameters(), max_norm=1.0)
        self.optimizer.step()
        self.scheduler.step()
        self.saved_log_probs = []
        self.rewards = []
        self.entropies = []


class EnhancedA2CAgent:
    """
    Улучшенный A2C: AdamW, cosine annealing, энтропийный бонус, gradient clipping.
    Actor и Critic представлены общей улучшенной сетью.
    """
    def __init__(self, n_warehouses, learning_rate=0.001, gamma=0.99, entropy_coef=0.01):
        self.actor_critic = EnhancedActorCriticNetwork(n_warehouses)
        self.optimizer = optim.AdamW(self.actor_critic.parameters(), lr=learning_rate, weight_decay=1e-4)
        self.scheduler = optim.lr_scheduler.CosineAnnealingLR(self.optimizer, T_max=1500)
        self.gamma = gamma
        self.entropy_coef = entropy_coef
        self.saved_log_probs = []
        self.rewards = []
        self.state_values = []
        self.entropies = []

    def select_action(self, state):
        """Выбирает действие, сохраняет log_prob, V(s) и энтропию."""
        state_tensor = {
            'current': torch.tensor([state['current']], dtype=torch.long),
            'visited_mask': torch.tensor([state['visited_mask']], dtype=torch.float32),
            'dist_vector': torch.tensor([state['dist_vector']], dtype=torch.float32)
        }
        probs, state_value = self.actor_critic(state_tensor)
        m = dist.Categorical(probs)
        action = m.sample()
        self.saved_log_probs.append(m.log_prob(action))
        self.state_values.append(state_value)
        self.entropies.append(m.entropy())
        return action.item()

    def update(self):
        """Обновление с преимуществами, MSE для критика и энтропийным бонусом."""
        if not self.rewards:
            return
        R = 0
        returns = []
        for r in reversed(self.rewards):
            R = r + self.gamma * R
            returns.insert(0, R)
        returns = torch.tensor(returns)
        returns = (returns - returns.mean()) / (returns.std() + 1e-8)
        state_values = torch.cat(self.state_values)
        advantages = returns - state_values.squeeze()
        policy_loss = []
        for log_prob, adv in zip(self.saved_log_probs, advantages):
            policy_loss.append(-log_prob * adv.detach())
        value_loss = nn.MSELoss()(state_values.squeeze(), returns)
        entropy = torch.stack(self.entropies).sum()
        loss = torch.stack(policy_loss).sum() + 0.5 * value_loss - self.entropy_coef * entropy
        self.optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(self.actor_critic.parameters(), max_norm=1.0)
        self.optimizer.step()
        self.scheduler.step()
        self.saved_log_probs = []
        self.rewards = []
        self.state_values = []
        self.entropies = []


class EnhancedPPOAgent:
    """
    Улучшенный PPO с несколькими эпохами обновления, энтропийным бонусом,
    cosine annealing и AdamW. Корректно использует пошаговые награды и done флаги.
    """
    def __init__(self, n_warehouses, learning_rate=0.0003, gamma=0.99, clip_epsilon=0.1, entropy_coef=0.02):
        self.actor_critic = EnhancedActorCriticNetwork(n_warehouses)
        self.optimizer = optim.AdamW(self.actor_critic.parameters(), lr=learning_rate, weight_decay=1e-4)
        self.scheduler = optim.lr_scheduler.CosineAnnealingLR(self.optimizer, T_max=1500)
        self.gamma = gamma
        self.clip_epsilon = clip_epsilon
        self.entropy_coef = entropy_coef
        self.memory = []   # хранит переходы эпизода

    def select_action(self, state):
        """Выбирает действие, сохраняет переход с пустыми reward/done (заполнятся позже)."""
        state_tensor = {
            'current': torch.tensor([state['current']], dtype=torch.long),
            'visited_mask': torch.tensor([state['visited_mask']], dtype=torch.float32),
            'dist_vector': torch.tensor([state['dist_vector']], dtype=torch.float32)
        }
        with torch.no_grad():
            probs, state_value = self.actor_critic(state_tensor)
            m = dist.Categorical(probs)
            action = m.sample()
        self.memory.append({
            'state': state_tensor,
            'action': action,
            'log_prob': m.log_prob(action),
            'value': state_value,
            'entropy': m.entropy(),
            'reward': 0.0,
            'done': False
        })
        return action.item()

    def set_last_reward(self, reward, done):
        """Заполняет reward и done для последнего сохранённого перехода."""
        if self.memory:
            self.memory[-1]['reward'] = reward
            self.memory[-1]['done'] = done

    def update(self):
        """
        Вычисляет returns с учётом done, преимущества, затем выполняет
        несколько эпох PPO‑обновления (clipped loss, value loss, энтропийный бонус).
        """
        if not self.memory:
            return
        rewards = [m['reward'] for m in self.memory]
        dones = [m['done'] for m in self.memory]
        states = [m['state'] for m in self.memory]
        actions = torch.stack([m['action'] for m in self.memory])
        old_log_probs = torch.stack([m['log_prob'] for m in self.memory])
        old_values = torch.cat([m['value'] for m in self.memory])
        old_entropies = torch.stack([m['entropy'] for m in self.memory])

        # вычисляем returns с учётом done (обнуляем R после done)
        returns = []
        R = 0
        for r, d in zip(reversed(rewards), reversed(dones)):
            if d:
                R = 0
            R = r + self.gamma * R
            returns.insert(0, R)
        returns = torch.tensor(returns, dtype=torch.float32)
        advantages = returns - old_values.squeeze()
        advantages = (advantages - advantages.mean()) / (advantages.std() + 1e-8)

        # несколько эпох обучения на одном эпизоде
        for _ in range(4):
            new_log_probs = []
            new_values = []
            new_entropies = []
            for i, state in enumerate(states):
                probs, value = self.actor_critic(state)
                d = dist.Categorical(probs)
                new_log_probs.append(d.log_prob(actions[i]))
                new_values.append(value)
                new_entropies.append(d.entropy())
            new_log_probs = torch.stack(new_log_probs)
            new_values = torch.cat(new_values)
            new_entropies = torch.stack(new_entropies)
            ratio = (new_log_probs - old_log_probs).exp()
            surr1 = ratio * advantages
            surr2 = torch.clamp(ratio, 1 - self.clip_epsilon, 1 + self.clip_epsilon) * advantages
            policy_loss = -torch.min(surr1, surr2).mean()
            value_loss = nn.MSELoss()(new_values.squeeze(), returns)
            entropy_bonus = -self.entropy_coef * new_entropies.mean()
            loss = policy_loss + 0.5 * value_loss + entropy_bonus
            self.optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(self.actor_critic.parameters(), max_norm=1.0)
            self.optimizer.step()
        self.scheduler.step()
        self.memory = []


class ImprovedDQNAgent:
    """
    Улучшенный DQN с Duelling архитектурой, Prioritized Experience Replay,
    мягким обновлением целевой сети, AdamW, cosine annealing,
    опционально Noisy сетями вместо ε‑greedy.
    """
    def __init__(self, n_warehouses, learning_rate=0.0003, gamma=0.99, tau=0.005, use_per=True, use_noisy=False):
        self.use_noisy = use_noisy
        if use_noisy:
            self.q_network = NoisyDuelingQNetwork(n_warehouses)
            self.target_network = NoisyDuelingQNetwork(n_warehouses)
        else:
            self.q_network = DuelingQNetwork(n_warehouses)
            self.target_network = DuelingQNetwork(n_warehouses)
        self.target_network.load_state_dict(self.q_network.state_dict())
        self.optimizer = optim.AdamW(self.q_network.parameters(), lr=learning_rate, weight_decay=1e-4)
        self.scheduler = optim.lr_scheduler.CosineAnnealingLR(self.optimizer, T_max=1500)
        self.gamma = gamma
        self.tau = tau          # коэффициент мягкого обновления целевой сети
        self.use_per = use_per
        if use_per:
            self.memory = PrioritizedReplayBuffer(capacity=10000, alpha=0.6)
            self.beta = 0.4
            self.beta_increment = 0.001
        else:
            self.memory = deque(maxlen=10000)
        self.batch_size = 128
        if not use_noisy:
            self.epsilon = 1.0
            self.epsilon_decay = 0.995
            self.epsilon_min = 0.01
        else:
            self.epsilon = 0.0   # не нужен при Noisy

    def select_action(self, state):
        """Выбор действия: ε‑greedy или argmax по Noisy сети."""
        if not self.use_noisy and random.random() < self.epsilon:
            visited = state['visited_mask']
            valid = [i for i, v in enumerate(visited) if v == 0]
            return random.choice(valid) if valid else 0
        state_tensor = {
            'current': torch.tensor([state['current']], dtype=torch.long),
            'visited_mask': torch.tensor([state['visited_mask']], dtype=torch.float32),
            'dist_vector': torch.tensor([state['dist_vector']], dtype=torch.float32)
        }
        with torch.no_grad():
            q_values = self.q_network(state_tensor)
            return q_values.argmax().item()

    def store_experience(self, state, action, reward, next_state, done):
        """Добавляет переход в PER‑буфер или обычный deque."""
        experience = (state, action, reward, next_state, done)
        if self.use_per:
            priority = self.memory.max_priority()
            self.memory.add(experience, priority)
        else:
            self.memory.append(experience)

    def update(self):
        """Обучает Q‑сеть на батче с возможной коррекцией по важности (PER)."""
        if len(self.memory) < self.batch_size:
            return
        if self.use_per:
            batch, indices, weights = self.memory.sample(self.batch_size, self.beta)
            if len(batch) < self.batch_size:
                return
            self.beta = min(1.0, self.beta + self.beta_increment)
            weights = torch.tensor(weights, dtype=torch.float32)
        else:
            batch = random.sample(list(self.memory), min(self.batch_size, len(self.memory)))
            weights = torch.ones(len(batch))
        states, actions, rewards, next_states, dones = zip(*batch)
        # Извлекаем компоненты состояния (учитываем dist_vector)
        state_current = torch.tensor([s['current'] for s in states], dtype=torch.long)
        state_visited = torch.tensor([s['visited_mask'] for s in states], dtype=torch.float32)
        state_distvec = torch.tensor([s['dist_vector'] for s in states], dtype=torch.float32)
        next_current = torch.tensor([s['current'] for s in next_states], dtype=torch.long)
        next_visited = torch.tensor([s['visited_mask'] for s in next_states], dtype=torch.float32)
        next_distvec = torch.tensor([s['dist_vector'] for s in next_states], dtype=torch.float32)
        state_tensors = {'current': state_current, 'visited_mask': state_visited, 'dist_vector': state_distvec}
        next_tensors = {'current': next_current, 'visited_mask': next_visited, 'dist_vector': next_distvec}
        actions = torch.tensor(actions)
        rewards = torch.tensor(rewards, dtype=torch.float32)
        dones = torch.tensor(dones, dtype=torch.float32)

        # Double DQN: выбор действия по основной сети, оценка по целевой
        with torch.no_grad():
            next_actions = self.q_network(next_tensors).argmax(1)
            next_q = self.target_network(next_tensors)[torch.arange(len(batch)), next_actions]
            targets = rewards + self.gamma * next_q * (1 - dones)
        current_q = self.q_network(state_tensors)[torch.arange(len(batch)), actions]
        td_errors = targets - current_q
        loss = (weights * td_errors.pow(2)).mean()
        self.optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(self.q_network.parameters(), max_norm=1.0)
        self.optimizer.step()
        self.scheduler.step()

        # мягкое обновление целевой сети
        for target_param, param in zip(self.target_network.parameters(), self.q_network.parameters()):
            target_param.data.copy_(self.tau * param.data + (1 - self.tau) * target_param.data)

        if self.use_per:
            self.memory.update_priorities(indices, td_errors.detach().abs().numpy())
        if self.use_noisy and hasattr(self.q_network, 'reset_noise'):
            self.q_network.reset_noise()
            self.target_network.reset_noise()
        if not self.use_noisy:
            self.epsilon = max(self.epsilon_min, self.epsilon * self.epsilon_decay)


class ImprovedDoubleDQNAgent(ImprovedDQNAgent):
    """
    Улучшенный Double DQN с увеличенным батчем, мягким обновлением таргет-сети
    и периодическим жёстким копированием весов для стабильности.
    """
    def __init__(self, n_warehouses, learning_rate=0.0003, gamma=0.99, tau=0.001, use_per=True, use_noisy=False):
        super().__init__(n_warehouses, learning_rate, gamma, tau, use_per, use_noisy)
        self.batch_size = 256
        self.tau = tau
        self.update_step = 0

    def update(self):
        """Выполняет обновление DQN и раз в 1000 шагов жёстко копирует веса."""
        super().update()
        self.update_step += 1
        if self.update_step % 1000 == 0:
            self.target_network.load_state_dict(self.q_network.state_dict())


class EnhancedSACAgent:
    """
    Улучшенный Soft Actor‑Critic для дискретных действий:
    автоматическая настройка энтропийного коэффициента α,
    дуэльные Q‑сети, PER, AdamW, cosine annealing.
    """
    def __init__(self, n_warehouses, learning_rate=0.0003, gamma=0.99, tau=0.005, alpha=0.2, use_per=True):
        self.actor = EnhancedPolicyNetwork(n_warehouses)           # политика
        self.critic1 = EnhancedSACNetwork(n_warehouses)            # первый критик
        self.critic2 = EnhancedSACNetwork(n_warehouses)            # второй критик
        self.critic1_target = EnhancedSACNetwork(n_warehouses)     # целевые сети
        self.critic2_target = EnhancedSACNetwork(n_warehouses)
        self.critic1_target.load_state_dict(self.critic1.state_dict())
        self.critic2_target.load_state_dict(self.critic2.state_dict())
        self.actor_optimizer = optim.AdamW(self.actor.parameters(), lr=learning_rate, weight_decay=1e-4)
        self.critic1_optimizer = optim.AdamW(self.critic1.parameters(), lr=learning_rate, weight_decay=1e-4)
        self.critic2_optimizer = optim.AdamW(self.critic2.parameters(), lr=learning_rate, weight_decay=1e-4)
        self.actor_scheduler = optim.lr_scheduler.CosineAnnealingLR(self.actor_optimizer, T_max=1500)
        self.critic1_scheduler = optim.lr_scheduler.CosineAnnealingLR(self.critic1_optimizer, T_max=1500)
        self.critic2_scheduler = optim.lr_scheduler.CosineAnnealingLR(self.critic2_optimizer, T_max=1500)
        self.gamma = gamma
        self.tau = tau
        self.target_entropy = -np.log(1.0 / n_warehouses) * 0.98   # желаемый уровень энтропии
        # log α – обучаемый параметр температуры; инициализируем на CPU, при использовании перенесём на нужное устройство
        self.log_alpha = torch.tensor(np.log(alpha), requires_grad=True, dtype=torch.float32)
        self.alpha_optimizer = optim.AdamW([self.log_alpha], lr=learning_rate)
        self.use_per = use_per
        if use_per:
            self.memory = PrioritizedReplayBuffer(capacity=10000, alpha=0.6)
            self.beta = 0.4
            self.beta_increment = 0.001
        else:
            self.memory = deque(maxlen=10000)
        self.batch_size = 256

    def select_action(self, state):
        """Сэмплирует действие из политики."""
        state_tensor = {
            'current': torch.tensor([state['current']], dtype=torch.long),
            'visited_mask': torch.tensor([state['visited_mask']], dtype=torch.float32),
            'dist_vector': torch.tensor([state['dist_vector']], dtype=torch.float32)
        }
        probs = self.actor(state_tensor)
        m = dist.Categorical(probs)
        action = m.sample()
        return action.item()

    def store_experience(self, state, action, reward, next_state, done):
        """Сохраняет переход с приоритетом."""
        experience = (state, action, reward, next_state, done)
        if self.use_per:
            priority = self.memory.max_priority()
            self.memory.add(experience, priority)
        else:
            self.memory.append(experience)

    def _soft_update(self, target, source):
        """Мягкое обновление целевых сетей."""
        for target_param, param in zip(target.parameters(), source.parameters()):
            target_param.data.copy_(self.tau * param.data + (1 - self.tau) * target_param.data)

    def update(self):
        """Обучает критиков и актора с автоматической настройкой α."""
        if len(self.memory) < self.batch_size:
            return
        if self.use_per:
            batch, indices, weights = self.memory.sample(self.batch_size, self.beta)
            if len(batch) < self.batch_size:
                return
            self.beta = min(1.0, self.beta + self.beta_increment)
            weights = torch.tensor(weights, dtype=torch.float32)
        else:
            batch = random.sample(list(self.memory), min(self.batch_size, len(self.memory)))
            weights = torch.ones(len(batch))
        states, actions, rewards, next_states, dones = zip(*batch)
        # Преобразуем состояния с учётом dist_vector
        state_current = torch.tensor([s['current'] for s in states], dtype=torch.long)
        state_visited = torch.tensor([s['visited_mask'] for s in states], dtype=torch.float32)
        state_distvec = torch.tensor([s['dist_vector'] for s in states], dtype=torch.float32)
        next_current = torch.tensor([s['current'] for s in next_states], dtype=torch.long)
        next_visited = torch.tensor([s['visited_mask'] for s in next_states], dtype=torch.float32)
        next_distvec = torch.tensor([s['dist_vector'] for s in next_states], dtype=torch.float32)
        state_tensors = {'current': state_current, 'visited_mask': state_visited, 'dist_vector': state_distvec}
        next_tensors = {'current': next_current, 'visited_mask': next_visited, 'dist_vector': next_distvec}
        actions = torch.tensor(actions)
        rewards = torch.tensor(rewards, dtype=torch.float32)
        dones = torch.tensor(dones, dtype=torch.float32)

        # Переносим log_alpha на нужное устройство, если ещё не там
        if self.log_alpha.device != state_current.device:
            self.log_alpha = self.log_alpha.to(state_current.device)
        alpha = self.log_alpha.exp()

        # Вычисляем target для критика
        with torch.no_grad():
            next_probs = self.actor(next_tensors)
            next_log_probs = torch.log(next_probs + 1e-8)
            next_q1 = self.critic1_target(next_tensors)
            next_q2 = self.critic2_target(next_tensors)
            next_q = torch.min(next_q1, next_q2)
            next_value = (next_probs * (next_q - alpha * next_log_probs)).sum(dim=1)
            targets = rewards + self.gamma * next_value * (1 - dones)

        # Лосс критиков
        current_q1 = self.critic1(state_tensors)[torch.arange(len(batch)), actions]
        current_q2 = self.critic2(state_tensors)[torch.arange(len(batch)), actions]
        critic1_loss = (weights * (current_q1 - targets).pow(2)).mean()
        critic2_loss = (weights * (current_q2 - targets).pow(2)).mean()
        self.critic1_optimizer.zero_grad()
        critic1_loss.backward()
        torch.nn.utils.clip_grad_norm_(self.critic1.parameters(), max_norm=1.0)
        self.critic1_optimizer.step()
        self.critic2_optimizer.zero_grad()
        critic2_loss.backward()
        torch.nn.utils.clip_grad_norm_(self.critic2.parameters(), max_norm=1.0)
        self.critic2_optimizer.step()

        # Лосс актора
        probs = self.actor(state_tensors)
        log_probs = torch.log(probs + 1e-8)
        with torch.no_grad():
            q1 = self.critic1(state_tensors)
            q2 = self.critic2(state_tensors)
            q = torch.min(q1, q2)
        actor_loss = (probs * (alpha.detach() * log_probs - q)).sum(dim=1).mean()
        self.actor_optimizer.zero_grad()
        actor_loss.backward()
        torch.nn.utils.clip_grad_norm_(self.actor.parameters(), max_norm=1.0)
        self.actor_optimizer.step()

        # Автоматическая настройка α
        alpha_loss = -(self.log_alpha * (log_probs.detach().mean() + self.target_entropy)).mean()
        self.alpha_optimizer.zero_grad()
        alpha_loss.backward()
        self.alpha_optimizer.step()

        # Мягкое обновление целевых сетей
        self._soft_update(self.critic1_target, self.critic1)
        self._soft_update(self.critic2_target, self.critic2)

        self.actor_scheduler.step()
        self.critic1_scheduler.step()
        self.critic2_scheduler.step()

        if self.use_per:
            td_errors = torch.abs(targets - current_q1).detach().numpy()
            self.memory.update_priorities(indices, td_errors)