# -*- coding: utf-8 -*-
"""classical

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fieia9ajSDi5Q2wJcqCJOaX1ZttON7HE

# classical.py
"""

# classical.py
# Классические эвристические и метаэвристические алгоритмы для ATSP
# Добавлено точное решение (Held-Karp) для малых размерностей,
# функции анализа и визуализации, запуск на 12 и 29 складах.

import os
import numpy as np
import pandas as pd
import time
import random
import matplotlib.pyplot as plt
import networkx as nx
from utils import (
    calculate_route_distance, INF, load_warehouses_from_json,
    zip_folder, unzip_all, validate_route_on_graph, plot_route_on_map
)

# 1. Жадный алгоритм (ближайший сосед)
def greedy_tsp(distance_matrix, start_index=0):
    """
    Жадный алгоритм ближайшего соседа для ATSP.

    Алгоритм:
        1. Начинаем со start_index.
        2. На каждом шаге выбираем непосещённый склад с минимальным расстоянием
           от текущего.
        3. После посещения всех складов возвращаемся в начальную точку.

    Параметры:
        distance_matrix (np.ndarray): квадратная асимметричная матрица расстояний
        start_index (int): индекс начального склада (по умолчанию 0)

    Возвращает:
        route (list): маршрут (список индексов), начинается и заканчивается start_index
        total_distance (float): длина маршрута в метрах
        exec_time (float): время выполнения в секундах
    """
    start_time = time.time()
    n = distance_matrix.shape[0]
    visited = [False] * n
    route = [start_index]
    visited[start_index] = True
    current = start_index

    while len(route) < n:
        best_dist = np.inf
        best_city = -1
        for nxt in range(n):
            if not visited[nxt] and distance_matrix[current][nxt] < best_dist:
                best_dist = distance_matrix[current][nxt]
                best_city = nxt
        route.append(best_city)
        visited[best_city] = True
        current = best_city

    route.append(start_index)
    total_distance = calculate_route_distance(route, distance_matrix)
    exec_time = time.time() - start_time
    return route, total_distance, exec_time

# 2. Алгоритм 2-OPT (локальный поиск)
def tsp_2opt(route, distance_matrix, max_iterations=1000):
    """
    Улучшение существующего маршрута с помощью 2-OPT перестановок.

    Алгоритм:
        1. Итеративно перебираем пары рёбер (i,i+1) и (j,j+1).
        2. Если замена рёбер (i,j) и (i+1,j+1) уменьшает длину, выполняем её.
        3. Повторяем, пока есть улучшения или не достигнут лимит итераций.

    Параметры:
        route (list): исходный маршрут (список индексов, начало=конец)
        distance_matrix (np.ndarray): асимметричная матрица расстояний
        max_iterations (int): максимальное количество глобальных итераций

    Возвращает:
        best_route (list): улучшенный маршрут
        best_distance (float): длина в метрах
        exec_time (float): время выполнения в секундах
    """
    start_time = time.time()
    best_route = route.copy()
    best_distance = calculate_route_distance(best_route, distance_matrix)
    improved = True
    iteration = 0

    while improved and iteration < max_iterations:
        improved = False
        for i in range(1, len(best_route) - 2):
            for j in range(i + 1, len(best_route) - 1):
                if j - i == 1:
                    continue
                new_route = best_route[:i] + best_route[i:j+1][::-1] + best_route[j+1:]
                new_distance = calculate_route_distance(new_route, distance_matrix)
                if new_distance < best_distance:
                    best_route = new_route
                    best_distance = new_distance
                    improved = True
                    break
            if improved:
                break
        iteration += 1

    exec_time = time.time() - start_time
    return best_route, best_distance, exec_time

# 3. Поиск с запретами (Tabu Search)
def tabu_search_tsp(distance_matrix, start_index=0, max_iter=200, tabu_size=20, neighbor_size=50):
    """
    Поиск с запретами (Tabu Search) для ATSP.

    Параметры:
        distance_matrix (np.ndarray): асимметричная матрица расстояний
        start_index (int): начальный склад
        max_iter (int): количество итераций
        tabu_size (int): размер списка запретов
        neighbor_size (int): сколько соседей генерировать на каждой итерации

    Возвращает:
        best_route (list): лучший маршрут
        best_distance (float): его длина в метрах
        exec_time (float): время выполнения
    """
    start_time = time.time()
    n = distance_matrix.shape[0]

    initial_route, _, _ = greedy_tsp(distance_matrix, start_index)
    current_route = initial_route.copy()
    current_distance = calculate_route_distance(current_route, distance_matrix)
    best_route = current_route.copy()
    best_distance = current_distance

    tabu_set = set()
    tabu_list = []

    def get_neighbors(route):
        neighbors = []
        indices = list(range(1, len(route)-1))
        for _ in range(neighbor_size):
            i, j = sorted(random.sample(indices, 2))
            if j - i == 1:
                continue
            new_route = route[:i] + route[i:j+1][::-1] + route[j+1:]
            neighbors.append(new_route)
        for _ in range(neighbor_size // 2):
            i, j = random.sample(indices, 2)
            new_route = route.copy()
            new_route[i], new_route[j] = new_route[j], new_route[i]
            neighbors.append(new_route)
        return neighbors

    def route_hash(route):
        return tuple(route)

    for iteration in range(max_iter):
        neighbors = get_neighbors(current_route)
        best_candidate = None
        best_candidate_dist = np.inf
        best_candidate_hash = None

        for cand in neighbors:
            cand_hash = route_hash(cand)
            cand_dist = calculate_route_distance(cand, distance_matrix)
            if cand_hash in tabu_set:
                if cand_dist < best_distance:
                    best_candidate = cand
                    best_candidate_dist = cand_dist
                    best_candidate_hash = cand_hash
                    break
                else:
                    continue
            if cand_dist < best_candidate_dist:
                best_candidate = cand
                best_candidate_dist = cand_dist
                best_candidate_hash = cand_hash

        if best_candidate is None:
            best_candidate = neighbors[0]
            best_candidate_dist = calculate_route_distance(best_candidate, distance_matrix)
            best_candidate_hash = route_hash(best_candidate)

        current_route = best_candidate
        current_distance = best_candidate_dist

        if current_distance < best_distance:
            best_route = current_route.copy()
            best_distance = current_distance

        tabu_set.add(best_candidate_hash)
        tabu_list.append(best_candidate_hash)
        if len(tabu_list) > tabu_size:
            removed = tabu_list.pop(0)
            tabu_set.remove(removed)

    exec_time = time.time() - start_time
    return best_route, best_distance, exec_time

# 4. Метод минимального остовного дерева (MST)
def mst_tsp(distance_matrix, start_index=0):
    """
    Приближённое решение TSP через минимальное остовное дерево.

    Для асимметричной матрицы используется симметризация: w(i,j) = min(D[i][j], D[j][i]).
    """
    start_time = time.time()
    n = distance_matrix.shape[0]

    G = nx.Graph()
    for i in range(n):
        for j in range(i + 1, n):
            sym_weight = min(distance_matrix[i][j], distance_matrix[j][i])
            G.add_edge(i, j, weight=sym_weight)

    mst = nx.minimum_spanning_tree(G)
    dfs_route = list(nx.dfs_preorder_nodes(mst, source=start_index))

    visited_set = set(dfs_route)
    missing = [v for v in range(n) if v not in visited_set]
    if missing:
        dfs_route.extend(missing)

    dfs_route.append(start_index)
    total_distance = calculate_route_distance(dfs_route, distance_matrix)
    exec_time = time.time() - start_time
    return dfs_route, total_distance, exec_time

# 5. Генетический алгоритм
def genetic_algorithm_tsp(distance_matrix, start_index=0, pop_size=50,
                          generations=100, mutation_rate=0.1, elite_size=1):
    """
    Генетический алгоритм для решения асимметричной задачи коммивояжёра (ATSP).

    Алгоритм:
        1. Инициализация: создаётся начальная популяция случайных допустимых маршрутов,
           каждый из которых начинается и заканчивается в start_index.
        2. Оценка приспособленности (фитнес): для каждой особи вычисляется
           fitness = 1 / (длина_маршрута + ε). Чем короче маршрут, тем выше фитнес.
        3. Элитизм: elite_size лучших особей переходят в следующее поколение без изменений.
        4. Формирование нового поколения: пока размер новой популяции не достигнет pop_size,
           выполняются следующие шаги:
           a) Турнирный отбор двух родителей (размер турнира = 3).
           b) Упорядоченный кроссовер (Order Crossover, OX) для получения потомка.
           c) Мутация потомка с вероятностью mutation_rate (обмен двух случайных городов).
        5. Процесс повторяется в течение generations поколений.

    Параметры:
        distance_matrix (np.ndarray): квадратная асимметричная матрица расстояний (n x n).
        start_index (int): индекс начального склада, фиксированный на концах маршрута.
        pop_size (int): размер популяции (количество особей).
        generations (int): количество поколений (итераций эволюции).
        mutation_rate (float): вероятность мутации для каждой особи (в диапазоне [0, 1]).
        elite_size (int): количество лучших особей, переносимых в следующее поколение без изменений.

    Возвращает:
        best_route (list): лучший найденный маршрут (список индексов), начинается и заканчивается start_index.
        best_distance (float): длина лучшего маршрута в метрах.
        exec_time (float): время выполнения алгоритма в секундах.
    """
    start_time = time.time()
    n = distance_matrix.shape[0]

    def create_individual():
        others = list(range(n))
        others.remove(start_index)
        random.shuffle(others)
        route = [start_index] + others + [start_index]
        return route

    def fitness(route):
        dist = calculate_route_distance(route, distance_matrix)
        return 1.0 / (dist + 1e-9)

    def order_crossover(parent1, parent2):
        p1 = parent1[1:-1]
        p2 = parent2[1:-1]
        size = len(p1)
        child = [-1] * size
        start, end = sorted(random.sample(range(size), 2))
        child[start:end+1] = p1[start:end+1]
        pointer = (end + 1) % size
        for gene in p2:
            if gene not in child:
                while child[pointer] != -1:
                    pointer = (pointer + 1) % size
                child[pointer] = gene
        return [start_index] + child + [start_index]

    def mutate(route):
        if random.random() < mutation_rate:
            idx1, idx2 = random.sample(range(1, len(route)-1), 2)
            route[idx1], route[idx2] = route[idx2], route[idx1]
        return route

    population = [create_individual() for _ in range(pop_size)]
    best_route = None
    best_distance = float('inf')

    for generation in range(generations):
        fitness_values = [fitness(ind) for ind in population]

        gen_best_idx = np.argmax(fitness_values)
        gen_best_route = population[gen_best_idx]
        gen_best_dist = calculate_route_distance(gen_best_route, distance_matrix)

        if gen_best_dist < best_distance:
            best_distance = gen_best_dist
            best_route = gen_best_route.copy()

        new_population = []
        elite_indices = np.argsort(fitness_values)[-elite_size:]
        for idx in elite_indices:
            new_population.append(population[idx].copy())

        while len(new_population) < pop_size:
            tournament = random.sample(range(pop_size), 3)
            parent1_idx = max(tournament, key=lambda i: fitness_values[i])
            parent2_idx = max(tournament, key=lambda i: fitness_values[i])
            parent1 = population[parent1_idx]
            parent2 = population[parent2_idx]

            child = order_crossover(parent1, parent2)
            child = mutate(child)
            new_population.append(child)

        population = new_population

    exec_time = time.time() - start_time
    return best_route, best_distance, exec_time

def exact_atsp(distance_matrix, start_index=0):
    """
    Точное решение ATSP методом динамического программирования (Held-Karp).
    Подходит только для малых n (до 20-22).

    Параметры:
        distance_matrix (np.ndarray): квадратная асимметричная матрица (n x n)
        start_index (int): начальный склад (по умолчанию 0)

    Возвращает:
        route (list): оптимальный маршрут, начинающийся и заканчивающийся в start_index
        optimal_distance (float): длина оптимального маршрута в метрах
        exec_time (float): время выполнения в секундах
    """
    start_time = time.time()
    n = distance_matrix.shape[0]
    if n > 22:
        raise ValueError(f"Точное решение для n={n} потребует слишком много памяти (2^{n} состояний).")

    INF = 1e12
    dp = np.full((1 << n, n), INF, dtype=np.float64)
    parent = np.full((1 << n, n), -1, dtype=np.int32)

    dp[1 << start_index][start_index] = 0.0

    for mask in range(1 << n):
        if not (mask & (1 << start_index)):
            continue
        for i in range(n):
            if not (mask & (1 << i)):
                continue
            if dp[mask][i] >= INF:
                continue
            for j in range(n):
                if mask & (1 << j):
                    continue
                new_mask = mask | (1 << j)
                new_dist = dp[mask][i] + distance_matrix[i][j]
                if new_dist < dp[new_mask][j]:
                    dp[new_mask][j] = new_dist
                    parent[new_mask][j] = i

    full_mask = (1 << n) - 1
    best_dist = INF
    best_last = -1
    for i in range(n):
        if i == start_index:
            continue
        total = dp[full_mask][i] + distance_matrix[i][start_index]
        if total < best_dist:
            best_dist = total
            best_last = i

    # Восстановление маршрута
    route = []
    mask = full_mask
    last = best_last
    while last != -1:
        route.append(last)
        prev = parent[mask][last]
        mask = mask ^ (1 << last)
        last = prev
    route.reverse()
    # Теперь маршрут содержит все вершины, начиная со start_index (он будет первым)
    # Добавляем возврат в start_index для замыкания
    route.append(start_index)

    exec_time = time.time() - start_time
    return route, best_dist, exec_time